apiVersion: "v1"
kind: "Service"
metadata:
  name: "golang-helloworld-service"
  labels:
    app: "golang-helloworld"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "golang-helloworld"
  type: "ClusterIP"
